name: Resource Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  resource-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run resource-check
